System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.classProperties",
      "es7.decorators"
    ],
    "blacklist": []
  },
  paths: {
    "*": "src/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/dependencies.js": [
      "npm:react-dom@0.14.6",
      "npm:redux@3.0.5",
      "npm:react@0.14.6",
      "npm:redux-thunk@1.0.3",
      "npm:react-router-redux@2.1.0",
      "npm:react-router@2.0.0-rc5",
      "npm:babel-runtime@5.8.35/helpers/class-call-check",
      "npm:react-redux@4.0.6",
      "npm:babel-runtime@5.8.35/helpers/get",
      "npm:babel-runtime@5.8.35/helpers/inherits",
      "npm:babel-runtime@5.8.35/helpers/create-class",
      "npm:react-dom@0.14.6/index",
      "npm:react@0.14.6/react",
      "npm:redux-thunk@1.0.3/lib/index",
      "npm:redux@3.0.5/lib/index",
      "npm:react-router-redux@2.1.0/lib/index",
      "npm:react-router@2.0.0-rc5/lib/index",
      "npm:phone-formatter@0.0.2",
      "components/toggleButtonInput",
      "npm:react-redux@4.0.6/lib/index",
      "npm:babel-runtime@5.8.35/core-js/object/assign",
      "npm:react-bootstrap@0.28.2",
      "npm:babel-runtime@5.8.35/core-js/object/get-own-property-descriptor",
      "npm:babel-runtime@5.8.35/core-js/object/create",
      "npm:babel-runtime@5.8.35/core-js/object/define-property",
      "npm:babel-runtime@5.8.35/core-js/object/define-properties",
      "npm:immutable@3.7.6",
      "npm:babel-runtime@5.8.35/core-js/object/set-prototype-of",
      "npm:react@0.14.6/lib/ReactDOM",
      "npm:redux@3.0.5/lib/utils/compose",
      "npm:react@0.14.6/lib/React",
      "npm:redux@3.0.5/lib/createStore",
      "npm:redux@3.0.5/lib/utils/bindActionCreators",
      "npm:redux@3.0.5/lib/utils/applyMiddleware",
      "npm:react-router@2.0.0-rc5/lib/IndexLink",
      "npm:redux@3.0.5/lib/utils/combineReducers",
      "npm:react-router@2.0.0-rc5/lib/IndexRedirect",
      "npm:react-router@2.0.0-rc5/lib/Link",
      "npm:react-router@2.0.0-rc5/lib/IndexRoute",
      "npm:react-router@2.0.0-rc5/lib/Lifecycle",
      "npm:react-router@2.0.0-rc5/lib/History",
      "npm:react-router@2.0.0-rc5/lib/RouteContext",
      "npm:react-router@2.0.0-rc5/lib/Route",
      "npm:react-router@2.0.0-rc5/lib/Redirect",
      "npm:react-router@2.0.0-rc5/lib/RouterContext",
      "npm:react-router@2.0.0-rc5/lib/RouteUtils",
      "npm:react-router@2.0.0-rc5/lib/RoutingContext",
      "npm:react-router@2.0.0-rc5/lib/match",
      "npm:react-router@2.0.0-rc5/lib/Router",
      "npm:react-router@2.0.0-rc5/lib/useRoutes",
      "npm:react-router@2.0.0-rc5/lib/useRouterHistory",
      "npm:react-router@2.0.0-rc5/lib/browserHistory",
      "npm:react-router@2.0.0-rc5/lib/hashHistory",
      "npm:phone-formatter@0.0.2/index",
      "npm:react-router@2.0.0-rc5/lib/PropTypes",
      "npm:firebase@2.4.0",
      "npm:babel-runtime@5.8.35/core-js/object/keys",
      "npm:core-js@1.2.6/library/fn/object/assign",
      "npm:core-js@1.2.6/library/fn/object/get-own-property-descriptor",
      "npm:core-js@1.2.6/library/fn/object/create",
      "npm:core-js@1.2.6/library/fn/object/define-property",
      "npm:core-js@1.2.6/library/fn/object/define-properties",
      "npm:react-router@2.0.0-rc5/lib/PatternUtils",
      "npm:react-redux@4.0.6/lib/components/Provider",
      "npm:react-redux@4.0.6/lib/components/connect",
      "npm:react-router@2.0.0-rc5/lib/createMemoryHistory",
      "npm:core-js@1.2.6/library/fn/object/set-prototype-of",
      "npm:react-bootstrap@0.28.2/lib/index",
      "npm:immutable@3.7.6/dist/immutable",
      "npm:react@0.14.6/lib/ReactCurrentOwner",
      "npm:react@0.14.6/lib/ReactReconciler",
      "npm:react@0.14.6/lib/ReactDOMTextComponent",
      "npm:react@0.14.6/lib/ReactPerf",
      "npm:react@0.14.6/lib/ReactDefaultInjection",
      "npm:react@0.14.6/lib/ReactVersion",
      "npm:react@0.14.6/lib/renderSubtreeIntoContainer",
      "github:jspm/nodelibs-process@0.1.2",
      "npm:react@0.14.6/lib/ReactDOMServer",
      "npm:react@0.14.6/lib/ReactIsomorphic",
      "npm:react@0.14.6/lib/ReactInstanceHandles",
      "npm:react@0.14.6/lib/ReactMount",
      "npm:react@0.14.6/lib/ReactUpdates",
      "npm:react@0.14.6/lib/Object.assign",
      "npm:fbjs@0.6.1/lib/ExecutionEnvironment",
      "npm:react@0.14.6/lib/findDOMNode",
      "npm:redux@3.0.5/lib/utils/pick",
      "npm:redux@3.0.5/lib/utils/mapValues",
      "npm:redux@3.0.5/lib/utils/isPlainObject",
      "npm:core-js@1.2.6/library/modules/$.core",
      "npm:core-js@1.2.6/library/modules/$",
      "npm:react-redux@4.0.6/lib/utils/shallowEqual",
      "npm:react-redux@4.0.6/lib/utils/isPlainObject",
      "npm:hoist-non-react-statics@1.0.3",
      "npm:invariant@2.2.0",
      "npm:react-router@2.0.0-rc5/lib/getRouteParams",
      "npm:react-router@2.0.0-rc5/lib/createRouterHistory",
      "npm:axios@0.9.1",
      "npm:babel-runtime@5.8.35/core-js/symbol",
      "npm:history@2.0.0-rc2/lib/useBasename",
      "npm:core-js@1.2.6/library/fn/object/keys",
      "npm:core-js@1.2.6/library/modules/es6.object.assign",
      "npm:core-js@1.2.6/library/modules/es6.object.get-own-property-descriptor",
      "npm:fbjs@0.6.1/lib/warning",
      "npm:react-router@2.0.0-rc5/lib/deprecateObjectProperties",
      "npm:react-router@2.0.0-rc5/lib/RouterUtils",
      "npm:react-router@2.0.0-rc5/lib/warning",
      "npm:history@2.0.0-rc2/lib/useQueries",
      "npm:react-redux@4.0.6/lib/utils/storeShape",
      "npm:history@2.0.0-rc2/lib/createBrowserHistory",
      "npm:history@2.0.0-rc2/lib/createHashHistory",
      "npm:react-redux@4.0.6/lib/utils/wrapActionCreators",
      "npm:react@0.14.6/lib/deprecated",
      "npm:react-router@2.0.0-rc5/lib/createTransitionManager",
      "npm:babel-runtime@5.8.35/helpers/interop-require-default",
      "npm:babel-runtime@5.8.35/helpers/interop-require-wildcard",
      "npm:react-bootstrap@0.28.2/lib/utils/createChainedFunction",
      "npm:core-js@1.2.6/library/modules/es6.object.set-prototype-of",
      "npm:history@2.0.0-rc2/lib/createMemoryHistory",
      "npm:firebase@2.4.0/lib/firebase-web",
      "npm:react-bootstrap@0.28.2/lib/utils/childrenValueInputValidation",
      "npm:react-bootstrap@0.28.2/lib/utils/bootstrapUtils",
      "npm:react-bootstrap@0.28.2/lib/utils/ValidComponentChildren",
      "npm:react-bootstrap@0.28.2/lib/Alert",
      "npm:react-bootstrap@0.28.2/lib/Accordion",
      "npm:react-bootstrap@0.28.2/lib/Badge",
      "npm:react-bootstrap@0.28.2/lib/Breadcrumb",
      "npm:react-bootstrap@0.28.2/lib/ButtonGroup",
      "npm:react-bootstrap@0.28.2/lib/BreadcrumbItem",
      "npm:react-bootstrap@0.28.2/lib/Button",
      "npm:react-bootstrap@0.28.2/lib/ButtonInput",
      "npm:react-bootstrap@0.28.2/lib/ButtonToolbar",
      "npm:react-bootstrap@0.28.2/lib/Carousel",
      "npm:react-bootstrap@0.28.2/lib/Col",
      "npm:react-bootstrap@0.28.2/lib/CarouselItem",
      "npm:react-bootstrap@0.28.2/lib/CollapsibleNav",
      "npm:react-bootstrap@0.28.2/lib/DropdownButton",
      "npm:react-bootstrap@0.28.2/lib/Dropdown",
      "npm:react-bootstrap@0.28.2/lib/Glyphicon",
      "npm:react-bootstrap@0.28.2/lib/Grid",
      "npm:react-bootstrap@0.28.2/lib/Image",
      "npm:react-bootstrap@0.28.2/lib/Jumbotron",
      "npm:react-bootstrap@0.28.2/lib/Input",
      "npm:react-bootstrap@0.28.2/lib/Interpolate",
      "npm:react-bootstrap@0.28.2/lib/Label",
      "npm:react-bootstrap@0.28.2/lib/ListGroup",
      "npm:react-bootstrap@0.28.2/lib/ListGroupItem",
      "npm:react-bootstrap@0.28.2/lib/MenuItem",
      "npm:react-bootstrap@0.28.2/lib/Modal",
      "npm:react-bootstrap@0.28.2/lib/ModalFooter",
      "npm:react-bootstrap@0.28.2/lib/ModalBody",
      "npm:react-bootstrap@0.28.2/lib/ModalTitle",
      "npm:react-bootstrap@0.28.2/lib/ModalHeader",
      "npm:react-bootstrap@0.28.2/lib/NavBrand",
      "npm:react-bootstrap@0.28.2/lib/Nav",
      "npm:react-bootstrap@0.28.2/lib/NavDropdown",
      "npm:react-bootstrap@0.28.2/lib/NavbarBrand",
      "npm:react-bootstrap@0.28.2/lib/Navbar",
      "npm:react-bootstrap@0.28.2/lib/NavItem",
      "npm:react-bootstrap@0.28.2/lib/Overlay",
      "npm:react-bootstrap@0.28.2/lib/PageHeader",
      "npm:react-bootstrap@0.28.2/lib/OverlayTrigger",
      "npm:react-bootstrap@0.28.2/lib/PageItem",
      "npm:react-bootstrap@0.28.2/lib/Pager",
      "npm:react-bootstrap@0.28.2/lib/Pagination",
      "npm:react-bootstrap@0.28.2/lib/Popover",
      "npm:react-bootstrap@0.28.2/lib/PanelGroup",
      "npm:react-bootstrap@0.28.2/lib/ProgressBar",
      "npm:react-bootstrap@0.28.2/lib/Row",
      "npm:react-bootstrap@0.28.2/lib/Panel",
      "npm:react-bootstrap@0.28.2/lib/ResponsiveEmbed",
      "npm:react-bootstrap@0.28.2/lib/SafeAnchor",
      "npm:react-bootstrap@0.28.2/lib/SplitButton",
      "npm:react-bootstrap@0.28.2/lib/Table",
      "npm:react-bootstrap@0.28.2/lib/Tab",
      "npm:react-bootstrap@0.28.2/lib/Thumbnail",
      "npm:react-bootstrap@0.28.2/lib/Tooltip",
      "npm:react-bootstrap@0.28.2/lib/Well",
      "npm:react-bootstrap@0.28.2/lib/Tabs",
      "npm:react-bootstrap@0.28.2/lib/Collapse",
      "npm:react-bootstrap@0.28.2/lib/Fade",
      "npm:react-bootstrap@0.28.2/lib/FormControls/index",
      "npm:react@0.14.6/lib/escapeTextContentForBrowser",
      "npm:react@0.14.6/lib/ClientReactRootIndex",
      "npm:react@0.14.6/lib/ReactComponentBrowserEnvironment",
      "npm:react@0.14.6/lib/ReactRef",
      "npm:react@0.14.6/lib/DOMChildrenOperations",
      "npm:react@0.14.6/lib/DOMPropertyOperations",
      "npm:react@0.14.6/lib/setTextContent",
      "npm:react@0.14.6/lib/ChangeEventPlugin",
      "npm:react@0.14.6/lib/validateDOMNesting",
      "npm:react@0.14.6/lib/DefaultEventPluginOrder",
      "npm:react@0.14.6/lib/EnterLeaveEventPlugin",
      "npm:react@0.14.6/lib/HTMLDOMPropertyConfig",
      "npm:react@0.14.6/lib/ServerReactRootIndex",
      "npm:react@0.14.6/lib/ReactRootIndex",
      "npm:react@0.14.6/lib/ReactDOMFeatureFlags",
      "npm:react@0.14.6/lib/ReactInstanceMap",
      "npm:react@0.14.6/lib/ReactEmptyComponentRegistry",
      "npm:react@0.14.6/lib/shouldUpdateReactComponent",
      "npm:react@0.14.6/lib/ReactInjection",
      "npm:react@0.14.6/lib/ReactReconcileTransaction",
      "npm:react@0.14.6/lib/SVGDOMPropertyConfig",
      "npm:react@0.14.6/lib/ReactMarkupChecksum",
      "npm:fbjs@0.6.1/lib/containsNode",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:react@0.14.6/lib/ReactElement",
      "npm:fbjs@0.6.1/lib/invariant",
      "npm:react@0.14.6/lib/ReactBrowserEventEmitter",
      "npm:fbjs@0.6.1/lib/emptyObject",
      "npm:react@0.14.6/lib/ReactDefaultBatchingStrategy",
      "npm:react@0.14.6/lib/BeforeInputEventPlugin",
      "npm:react@0.14.6/lib/ReactDOMComponent",
      "npm:react@0.14.6/lib/ReactEventListener",
      "npm:react@0.14.6/lib/ReactBrowserComponentMixin",
      "npm:react@0.14.6/lib/SelectEventPlugin",
      "npm:react@0.14.6/lib/SimpleEventPlugin",
      "npm:react@0.14.6/lib/ReactDefaultPerf",
      "npm:react@0.14.6/lib/ReactServerRendering",
      "npm:react@0.14.6/lib/ReactChildren",
      "npm:react@0.14.6/lib/ReactComponent",
      "npm:react@0.14.6/lib/ReactDOMFactories",
      "npm:react@0.14.6/lib/ReactClass",
      "npm:react@0.14.6/lib/onlyChild",
      "npm:react@0.14.6/lib/ReactPropTypes",
      "npm:react@0.14.6/lib/DOMProperty",
      "npm:react@0.14.6/lib/ReactElementValidator",
      "npm:react@0.14.6/lib/ReactUpdateQueue",
      "npm:react@0.14.6/lib/instantiateReactComponent",
      "npm:react@0.14.6/lib/setInnerHTML",
      "npm:react@0.14.6/lib/CallbackQueue",
      "npm:react@0.14.6/lib/PooledClass",
      "npm:react@0.14.6/lib/Transaction",
      "npm:history@2.0.0-rc2/lib/ExecutionEnvironment",
      "npm:history@2.0.0-rc2/lib/extractPath",
      "npm:alertify.js@1.0.8",
      "npm:core-js@1.2.6/library/fn/symbol",
      "npm:axios@0.9.1/index",
      "npm:core-js@1.2.6/library/modules/es6.object.keys",
      "npm:history@2.0.0-rc2/lib/runTransitionHook",
      "npm:history@2.0.0-rc2/lib/deprecate",
      "npm:history@2.0.0-rc2/lib/parsePath",
      "npm:hoist-non-react-statics@1.0.3/index",
      "npm:fbjs@0.6.1/lib/emptyFunction",
      "npm:history@2.0.0-rc2/lib/Actions",
      "npm:history@2.0.0-rc2/lib/DOMUtils",
      "npm:babel-runtime@5.8.35/helpers/object-without-properties",
      "npm:classnames@2.2.3",
      "npm:core-js@1.2.6/library/modules/$.to-iobject",
      "npm:core-js@1.2.6/library/modules/$.object-sap",
      "npm:warning@2.1.0",
      "npm:query-string@3.0.0",
      "npm:react-router@2.0.0-rc5/lib/computeChangedRoutes",
      "npm:react-router@2.0.0-rc5/lib/isActive",
      "npm:react-router@2.0.0-rc5/lib/getComponents",
      "github:jspm/nodelibs-buffer@0.1.0",
      "npm:core-js@1.2.6/library/modules/$.export",
      "npm:babel-runtime@5.8.35/helpers/extends",
      "npm:core-js@1.2.6/library/modules/$.object-assign",
      "npm:core-js@1.2.6/library/modules/$.set-proto",
      "npm:history@2.0.0-rc2/lib/DOMStateStorage",
      "npm:history@2.0.0-rc2/lib/createDOMHistory",
      "npm:invariant@2.2.0/browser",
      "npm:react-router@2.0.0-rc5/lib/TransitionUtils",
      "npm:react-router@2.0.0-rc5/lib/matchRoutes",
      "npm:history@2.0.0-rc2/lib/createHistory",
      "npm:react-bootstrap@0.28.2/lib/styleMaps",
      "npm:react-bootstrap@0.28.2/lib/utils/TransitionEvents",
      "npm:react-prop-types@0.3.0/lib/singlePropFrom",
      "npm:react-prop-types@0.3.0/lib/all",
      "npm:react-prop-types@0.3.0/lib/isRequiredForA11y",
      "npm:dom-helpers@2.4.0/util/inDOM",
      "npm:dom-helpers@2.4.0/ownerDocument",
      "npm:dom-helpers@2.4.0/activeElement",
      "npm:dom-helpers@2.4.0/query/contains",
      "npm:keycode@2.1.0",
      "npm:dom-helpers@2.4.0/util/scrollbarSize",
      "npm:dom-helpers@2.4.0/events",
      "npm:dom-helpers@2.4.0/style",
      "npm:lodash-compat@3.10.2/object/pick",
      "npm:uncontrollable@3.2.1",
      "npm:lodash-compat@3.10.2/collection/find",
      "npm:lodash-compat@3.10.2/object/omit",
      "npm:react-prop-types@0.3.0/lib/elementType",
      "npm:react-overlays@0.5.4/lib/utils/isOverflowing",
      "npm:react-prop-types@0.3.0/lib/deprecated",
      "npm:react-overlays@0.5.4/lib/Transition",
      "npm:react-bootstrap@0.28.2/lib/FormGroup",
      "npm:react-bootstrap@0.28.2/lib/utils/deprecationWarning",
      "npm:react-bootstrap@0.28.2/lib/InputBase",
      "npm:react-bootstrap@0.28.2/lib/DropdownToggle",
      "npm:react-bootstrap@0.28.2/lib/DropdownMenu",
      "npm:react-bootstrap@0.28.2/lib/utils/CustomPropTypes",
      "npm:react-bootstrap@0.28.2/lib/ModalDialog",
      "npm:react-bootstrap@0.28.2/lib/deprecated/Navbar",
      "npm:react-bootstrap@0.28.2/lib/NavbarHeader",
      "npm:react-bootstrap@0.28.2/lib/NavbarToggle",
      "npm:react-bootstrap@0.28.2/lib/NavbarCollapse",
      "npm:react-overlays@0.5.4/lib/Modal",
      "npm:react-bootstrap@0.28.2/lib/SplitToggle",
      "npm:react-bootstrap@0.28.2/lib/FormControls/Static",
      "npm:react@0.14.6/lib/getEventTarget",
      "npm:react@0.14.6/lib/isTextInputElement",
      "npm:fbjs@0.6.1/lib/keyOf",
      "npm:react@0.14.6/lib/quoteAttributeValueForBrowser",
      "npm:react@0.14.6/lib/ReactMultiChildUpdateTypes",
      "npm:react@0.14.6/lib/ReactOwner",
      "npm:react-overlays@0.5.4/lib/Overlay",
      "npm:react@0.14.6/lib/ReactDOMIDOperations",
      "npm:react@0.14.6/lib/Danger",
      "npm:react@0.14.6/lib/EventConstants",
      "npm:react@0.14.6/lib/SyntheticEvent",
      "npm:react@0.14.6/lib/EventPluginHub",
      "npm:react@0.14.6/lib/isEventSupported",
      "npm:react-bootstrap@0.28.2/lib/PaginationButton",
      "npm:react@0.14.6/lib/EventPropagators",
      "npm:react@0.14.6/lib/SyntheticMouseEvent",
      "npm:react@0.14.6/lib/adler32",
      "npm:react@0.14.6/lib/ViewportMetrics",
      "npm:react@0.14.6/lib/ReactDOMButton",
      "npm:fbjs@0.6.1/lib/getUnboundedScrollPosition",
      "npm:fbjs@0.6.1/lib/shallowEqual",
      "npm:fbjs@0.6.1/lib/getActiveElement",
      "npm:react@0.14.6/lib/ReactEmptyComponent",
      "npm:fbjs@0.6.1/lib/isTextNode",
      "npm:process@0.11.2",
      "npm:react@0.14.6/lib/SyntheticCompositionEvent",
      "npm:react@0.14.6/lib/FallbackCompositionState",
      "npm:react@0.14.6/lib/ReactEventEmitterMixin",
      "npm:react@0.14.6/lib/SyntheticInputEvent",
      "npm:react@0.14.6/lib/SyntheticKeyboardEvent",
      "npm:react@0.14.6/lib/SyntheticFocusEvent",
      "npm:react@0.14.6/lib/SyntheticClipboardEvent",
      "npm:react@0.14.6/lib/SyntheticTouchEvent",
      "npm:react@0.14.6/lib/SyntheticDragEvent",
      "npm:react@0.14.6/lib/SyntheticUIEvent",
      "npm:react@0.14.6/lib/SyntheticWheelEvent",
      "npm:react@0.14.6/lib/canDefineProperty",
      "npm:react@0.14.6/lib/ReactMultiChild",
      "npm:fbjs@0.6.1/lib/EventListener",
      "npm:react@0.14.6/lib/ReactComponentEnvironment",
      "npm:react@0.14.6/lib/ReactInputSelection",
      "npm:react@0.14.6/lib/ReactNativeComponent",
      "npm:react@0.14.6/lib/AutoFocusUtils",
      "npm:react@0.14.6/lib/CSSPropertyOperations",
      "npm:react@0.14.6/lib/ReactDOMInput",
      "npm:react@0.14.6/lib/EventPluginRegistry",
      "npm:react@0.14.6/lib/ReactDOMOption",
      "npm:react@0.14.6/lib/ReactDOMSelect",
      "npm:react@0.14.6/lib/ReactDOMTextarea",
      "npm:react@0.14.6/lib/ReactServerBatchingStrategy",
      "npm:react@0.14.6/lib/getEventCharCode",
      "npm:react@0.14.6/lib/ReactDefaultPerfAnalysis",
      "npm:react@0.14.6/lib/ReactServerRenderingTransaction",
      "npm:react@0.14.6/lib/getIteratorFn",
      "npm:fbjs@0.6.1/lib/mapObject",
      "npm:fbjs@0.6.1/lib/performanceNow",
      "npm:react@0.14.6/lib/ReactPropTypeLocationNames",
      "npm:fbjs@0.6.1/lib/keyMirror",
      "npm:react@0.14.6/lib/traverseAllChildren",
      "npm:react@0.14.6/lib/ReactPropTypeLocations",
      "npm:react@0.14.6/lib/ReactNoopUpdateQueue",
      "npm:react@0.14.6/lib/ReactCompositeComponent",
      "npm:alertify.js@1.0.8/dist/js/alertify",
      "npm:core-js@1.2.6/library/modules/$.to-object",
      "npm:core-js@1.2.6/library/fn/symbol/index",
      "npm:axios@0.9.1/lib/axios",
      "npm:core-js@1.2.6/library/modules/$.fails",
      "npm:core-js@1.2.6/library/modules/$.defined",
      "npm:classnames@2.2.3/index",
      "npm:react-router@2.0.0-rc5/lib/AsyncUtils",
      "npm:core-js@1.2.6/library/modules/$.global",
      "npm:core-js@1.2.6/library/modules/$.is-object",
      "npm:history@2.0.0-rc2/lib/AsyncUtils",
      "npm:deep-equal@1.0.1",
      "npm:core-js@1.2.6/library/modules/$.iobject",
      "npm:core-js@1.2.6/library/modules/$.ctx",
      "npm:core-js@1.2.6/library/modules/$.an-object",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:keycode@2.1.0/index",
      "npm:dom-helpers@2.4.0/events/index",
      "npm:query-string@3.0.0/index",
      "npm:warning@2.1.0/browser",
      "npm:lodash-compat@3.10.2/internal/arrayMap",
      "npm:react-prop-types@0.3.0/lib/common",
      "npm:lodash-compat@3.10.2/function/restParam",
      "npm:dom-helpers@2.4.0/query/isWindow",
      "npm:react-overlays@0.5.4/lib/utils/addFocusListener",
      "npm:react@0.14.6/lib/forEachAccumulated",
      "npm:react-bootstrap@0.28.2/lib/utils/createSelectedEvent",
      "npm:dom-helpers@2.4.0/style/index",
      "npm:dom-helpers@2.4.0/events/on",
      "npm:lodash-compat@3.10.2/internal/pickByArray",
      "npm:lodash-compat@3.10.2/internal/pickByCallback",
      "npm:lodash-compat@3.10.2/internal/baseFlatten",
      "npm:uncontrollable@3.2.1/index",
      "npm:lodash-compat@3.10.2/internal/baseEach",
      "npm:lodash-compat@3.10.2/internal/createFind",
      "npm:lodash-compat@3.10.2/internal/bindCallback",
      "npm:lodash-compat@3.10.2/object/keysIn",
      "npm:lodash-compat@3.10.2/internal/baseDifference",
      "npm:react-prop-types@0.2.2/lib/elementType",
      "npm:react-prop-types@0.2.2/lib/mountable",
      "npm:react-overlays@0.5.4/lib/ModalManager",
      "npm:react-overlays@0.5.4/lib/utils/addEventListener",
      "npm:history@2.0.0-rc2/lib/createLocation",
      "npm:react-overlays@0.5.4/lib/RootCloseWrapper",
      "npm:react-overlays@0.5.4/lib/utils/ownerDocument",
      "npm:react-overlays@0.5.4/lib/utils/getContainer",
      "npm:fbjs@0.6.1/lib/createNodesFromMarkup",
      "npm:fbjs@0.6.1/lib/getMarkupWrap",
      "npm:react@0.14.6/lib/ReactErrorUtils",
      "npm:react-bootstrap@0.28.2/lib/utils/childrenToArray",
      "npm:react-overlays@0.5.4/lib/Portal",
      "npm:react-overlays@0.5.4/lib/Position",
      "npm:react@0.14.6/lib/accumulateInto",
      "npm:react@0.14.6/lib/getEventModifierState",
      "npm:fbjs@0.6.1/lib/isNode",
      "npm:dom-helpers@2.4.0/util/babelHelpers",
      "npm:fbjs@0.6.1/lib/focusNode",
      "npm:react@0.14.6/lib/CSSProperty",
      "npm:fbjs@0.6.1/lib/memoizeStringOnly",
      "npm:react@0.14.6/lib/getEventKey",
      "npm:fbjs@0.6.1/lib/camelizeStyleName",
      "npm:react@0.14.6/lib/dangerousStyleValue",
      "npm:fbjs@0.6.1/lib/hyphenateStyleName",
      "npm:react@0.14.6/lib/EventPluginUtils",
      "npm:react@0.14.6/lib/getTextContentAccessor",
      "npm:react@0.14.6/lib/ReactChildReconciler",
      "npm:react@0.14.6/lib/flattenChildren",
      "npm:react@0.14.6/lib/ReactDOMSelection",
      "npm:fbjs@0.6.1/lib/performance",
      "npm:react@0.14.6/lib/LinkedValueUtils",
      "npm:dom-helpers@2.4.0/transition/properties",
      "npm:core-js@1.2.6/library/modules/es6.object.to-string",
      "npm:core-js@1.2.6/library/modules/es6.symbol",
      "npm:axios@0.9.1/lib/defaults",
      "npm:process@0.11.2/browser",
      "npm:axios@0.9.1/lib/helpers/isAbsoluteURL",
      "npm:axios@0.9.1/lib/helpers/combineURLs",
      "npm:axios@0.9.1/lib/helpers/bind",
      "npm:axios@0.9.1/lib/helpers/spread",
      "npm:core-js@1.2.6/library/modules/$.cof",
      "npm:core-js@1.2.6/library/modules/$.a-function",
      "npm:axios@0.9.1/lib/utils",
      "npm:deep-equal@1.0.1/index",
      "npm:axios@0.9.1/lib/helpers/transformData",
      "npm:buffer@3.6.0",
      "npm:strict-uri-encode@1.1.0",
      "npm:dom-helpers@2.4.0/events/off",
      "npm:dom-helpers@2.4.0/events/filter",
      "npm:axios@0.9.1/lib/core/InterceptorManager",
      "npm:axios@0.9.1/lib/core/dispatchRequest",
      "npm:dom-helpers@2.4.0/style/removeStyle",
      "npm:lodash-compat@3.10.2/internal/arrayPush",
      "npm:lodash-compat@3.10.2/internal/isObjectLike",
      "npm:dom-helpers@2.4.0/util/hyphenateStyle",
      "npm:dom-helpers@2.4.0/util/camelizeStyle",
      "npm:lodash-compat@3.10.2/lang/isArguments",
      "npm:lodash-compat@3.10.2/internal/baseForIn",
      "npm:lodash-compat@3.10.2/internal/isArrayLike",
      "npm:lodash-compat@3.10.2/lang/isArray",
      "npm:lodash-compat@3.10.2/internal/baseForOwn",
      "npm:lodash-compat@3.10.2/internal/toObject",
      "npm:lodash-compat@3.10.2/internal/baseFind",
      "npm:lodash-compat@3.10.2/internal/arrayEach",
      "npm:lodash-compat@3.10.2/utility/identity",
      "npm:lodash-compat@3.10.2/internal/isLength",
      "npm:lodash-compat@3.10.2/internal/isIndex",
      "npm:lodash-compat@3.10.2/lang/isObject",
      "npm:react-prop-types@0.2.2/lib/common",
      "npm:react-overlays@0.5.4/lib/utils/manageAriaHidden",
      "npm:react-overlays@0.5.4/lib/utils/createChainedFunction",
      "npm:dom-helpers@2.4.0/style/getComputedStyle",
      "npm:dom-helpers@2.4.0/class",
      "npm:lodash-compat@3.10.2/internal/baseCallback",
      "npm:lodash-compat@3.10.2/lang/isFunction",
      "npm:lodash-compat@3.10.2/internal/createBaseEach",
      "npm:lodash-compat@3.10.2/lang/isString",
      "npm:lodash-compat@3.10.2/internal/baseIndexOf",
      "npm:lodash-compat@3.10.2/internal/cacheIndexOf",
      "npm:lodash-compat@3.10.2/internal/createCache",
      "npm:fbjs@0.6.1/lib/createArrayFromMixed",
      "npm:react-overlays@0.5.4/lib/utils/overlayPositionUtils",
      "npm:uncontrollable@3.2.1/createUncontrollable",
      "npm:fbjs@0.6.1/lib/hyphenate",
      "npm:lodash-compat@3.10.2/internal/baseFindIndex",
      "npm:react@0.14.6/lib/getNodeForCharacterOffset",
      "npm:lodash-compat@3.10.2/support",
      "npm:core-js@1.2.6/library/modules/$.has",
      "npm:core-js@1.2.6/library/modules/$.uid",
      "npm:core-js@1.2.6/library/modules/$.library",
      "npm:core-js@1.2.6/library/modules/$.property-desc",
      "npm:core-js@1.2.6/library/modules/$.descriptors",
      "npm:core-js@1.2.6/library/modules/$.shared",
      "npm:core-js@1.2.6/library/modules/$.set-to-string-tag",
      "npm:core-js@1.2.6/library/modules/$.redefine",
      "npm:core-js@1.2.6/library/modules/$.wks",
      "npm:core-js@1.2.6/library/modules/$.enum-keys",
      "npm:core-js@1.2.6/library/modules/$.keyof",
      "npm:core-js@1.2.6/library/modules/$.get-names",
      "npm:core-js@1.2.6/library/modules/$.is-array",
      "npm:fbjs@0.6.1/lib/camelize",
      "npm:deep-equal@1.0.1/lib/is_arguments",
      "npm:deep-equal@1.0.1/lib/keys",
      "npm:strict-uri-encode@1.1.0/index",
      "npm:buffer@3.6.0/index",
      "npm:dom-helpers@2.4.0/query/querySelectorAll",
      "npm:dom-helpers@2.4.0/util/hyphenate",
      "npm:dom-helpers@2.4.0/util/camelize",
      "npm:lodash-compat@3.10.2/internal/baseFor",
      "npm:lodash-compat@3.10.2/internal/getLength",
      "npm:lodash-compat@3.10.2/internal/getNative",
      "npm:lodash-compat@3.10.2/internal/indexOfNaN",
      "npm:dom-helpers@2.4.0/class/index",
      "npm:dom-helpers@2.4.0/query/scrollTop",
      "npm:lodash-compat@3.10.2/object/keys",
      "npm:lodash-compat@3.10.2/utility/property",
      "npm:lodash-compat@3.10.2/internal/SetCache",
      "npm:axios@0.9.1/lib/adapters/xhr",
      "npm:lodash-compat@3.10.2/internal/baseMatchesProperty",
      "npm:lodash-compat@3.10.2/internal/baseMatches",
      "npm:uncontrollable@3.2.1/utils",
      "npm:core-js@1.2.6/library/modules/$.hide",
      "npm:fbjs@0.6.1/lib/toArray",
      "npm:base64-js@0.0.8",
      "npm:ieee754@1.1.6",
      "npm:isarray@1.0.0",
      "npm:dom-helpers@2.4.0/query/offset",
      "npm:dom-helpers@2.4.0/class/removeClass",
      "npm:dom-helpers@2.4.0/class/hasClass",
      "npm:axios@0.9.1/lib/helpers/btoa",
      "npm:lodash-compat@3.10.2/array/last",
      "npm:dom-helpers@2.4.0/query/position",
      "npm:dom-helpers@2.4.0/class/addClass",
      "npm:lodash-compat@3.10.2/internal/createBaseFor",
      "npm:lodash-compat@3.10.2/lang/isNative",
      "npm:lodash-compat@3.10.2/internal/baseProperty",
      "npm:lodash-compat@3.10.2/internal/basePropertyDeep",
      "npm:lodash-compat@3.10.2/internal/cachePush",
      "npm:lodash-compat@3.10.2/internal/isKey",
      "npm:axios@0.9.1/lib/helpers/buildURL",
      "npm:axios@0.9.1/lib/helpers/parseHeaders",
      "npm:axios@0.9.1/lib/helpers/isURLSameOrigin",
      "npm:axios@0.9.1/lib/helpers/cookies",
      "npm:lodash-compat@3.10.2/internal/baseGet",
      "npm:lodash-compat@3.10.2/internal/baseIsEqual",
      "npm:lodash-compat@3.10.2/internal/isStrictComparable",
      "npm:lodash-compat@3.10.2/internal/getMatchData",
      "npm:lodash-compat@3.10.2/internal/toPath",
      "npm:lodash-compat@3.10.2/internal/baseSlice",
      "npm:isarray@1.0.0/index",
      "npm:lodash-compat@3.10.2/internal/shimKeys",
      "npm:lodash-compat@3.10.2/internal/baseIsMatch",
      "npm:lodash-compat@3.10.2/internal/isHostObject",
      "npm:ieee754@1.1.6/index",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:dom-helpers@2.4.0/query/scrollLeft",
      "npm:lodash-compat@3.10.2/object/pairs",
      "npm:lodash-compat@3.10.2/internal/baseToString",
      "npm:dom-helpers@2.4.0/query/offsetParent",
      "npm:lodash-compat@3.10.2/internal/baseIsEqualDeep",
      "npm:lodash-compat@3.10.2/internal/equalByTag",
      "npm:lodash-compat@3.10.2/internal/equalObjects",
      "npm:lodash-compat@3.10.2/internal/equalArrays",
      "npm:lodash-compat@3.10.2/lang/isTypedArray",
      "npm:lodash-compat@3.10.2/internal/arraySome"
    ]
  },

  map: {
    "alertify.js": "npm:alertify.js@1.0.8",
    "axios": "npm:axios@0.9.1",
    "babel": "npm:babel-core@5.8.34",
    "babel-runtime": "npm:babel-runtime@5.8.35",
    "core-js": "npm:core-js@1.2.6",
    "firebase": "npm:firebase@2.4.0",
    "immutable": "npm:immutable@3.7.6",
    "phone-formatter": "npm:phone-formatter@0.0.2",
    "react": "npm:react@0.14.6",
    "react-bootstrap": "npm:react-bootstrap@0.28.2",
    "react-dom": "npm:react-dom@0.14.6",
    "react-redux": "npm:react-redux@4.0.6",
    "react-router": "npm:react-router@2.0.0-rc5",
    "react-router-redux": "npm:react-router-redux@2.1.0",
    "redux": "npm:redux@3.0.5",
    "redux-devtools": "npm:redux-devtools@3.0.1",
    "redux-thunk": "npm:redux-thunk@1.0.3",
    "sleep-promise": "npm:sleep-promise@1.0.0",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.11.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-net@0.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "timers": "github:jspm/nodelibs-timers@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-timers@0.1.0": {
      "timers-browserify": "npm:timers-browserify@1.4.2"
    },
    "github:jspm/nodelibs-tty@0.1.0": {
      "tty-browserify": "npm:tty-browserify@0.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:asn1.js@4.3.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:axios@0.9.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "follow-redirects": "npm:follow-redirects@0.0.7",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:babel-runtime@5.8.35": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:browserify-aes@1.0.6": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:browserify-sign@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.8",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.0.5",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:cipher-base@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@1.2.6": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@6.2.3"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.11.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@4.0.0",
      "create-ecdh": "npm:create-ecdh@4.0.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@5.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@4.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:debug@2.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ms": "npm:ms@0.7.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "tty": "github:jspm/nodelibs-tty@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@5.0.2": {
      "bn.js": "npm:bn.js@4.9.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@4.0.0",
      "randombytes": "npm:randombytes@2.0.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@6.2.3": {
      "bn.js": "npm:bn.js@4.9.0",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:faye-websocket@0.10.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "tls": "github:jspm/nodelibs-tls@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "websocket-driver": "npm:websocket-driver@0.6.4"
    },
    "npm:fbjs@0.6.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:firebase@2.4.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "faye-websocket": "npm:faye-websocket@0.10.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:follow-redirects@0.0.7": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "debug": "npm:debug@2.2.0",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-consume": "npm:stream-consume@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:history@2.0.0-rc2": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "deep-equal": "npm:deep-equal@1.0.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "query-string": "npm:query-string@3.0.0",
      "warning": "npm:warning@2.1.0"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash-compat@3.10.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:lodash@3.10.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:loose-envify@1.1.0": {
      "js-tokens": "npm:js-tokens@1.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:pako@0.2.8": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:parse-asn1@5.0.0": {
      "asn1.js": "npm:asn1.js@4.3.0",
      "browserify-aes": "npm:browserify-aes@1.0.6",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process-nextick-args@1.0.6": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@4.0.0": {
      "bn.js": "npm:bn.js@4.9.0",
      "browserify-rsa": "npm:browserify-rsa@4.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@5.0.0",
      "randombytes": "npm:randombytes@2.0.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:query-string@3.0.0": {
      "strict-uri-encode": "npm:strict-uri-encode@1.1.0"
    },
    "npm:randombytes@2.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-bootstrap@0.28.2": {
      "babel-runtime": "npm:babel-runtime@5.8.35",
      "classnames": "npm:classnames@2.2.3",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "invariant": "npm:invariant@2.2.0",
      "keycode": "npm:keycode@2.1.0",
      "lodash-compat": "npm:lodash-compat@3.10.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.6",
      "react-dom": "npm:react-dom@0.14.6",
      "react-overlays": "npm:react-overlays@0.5.4",
      "react-prop-types": "npm:react-prop-types@0.3.0",
      "uncontrollable": "npm:uncontrollable@3.2.1",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-dom@0.14.6": {
      "react": "npm:react@0.14.6"
    },
    "npm:react-overlays@0.5.4": {
      "classnames": "npm:classnames@2.2.3",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "react": "npm:react@0.14.6",
      "react-dom": "npm:react-dom@0.14.6",
      "react-prop-types": "npm:react-prop-types@0.2.2",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-prop-types@0.2.2": {
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-prop-types@0.3.0": {
      "warning": "npm:warning@2.1.0"
    },
    "npm:react-redux@4.0.6": {
      "hoist-non-react-statics": "npm:hoist-non-react-statics@1.0.3",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.6",
      "redux": "npm:redux@3.0.5"
    },
    "npm:react-router@2.0.0-rc5": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "history": "npm:history@2.0.0-rc2",
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "warning": "npm:warning@2.1.0"
    },
    "npm:react@0.14.6": {
      "fbjs": "npm:fbjs@0.6.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.6",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:redux-devtools@3.0.1": {
      "lodash": "npm:lodash@3.10.1",
      "react": "npm:react@0.14.6",
      "react-redux": "npm:react-redux@4.0.6",
      "redux": "npm:redux@3.0.5"
    },
    "npm:redux@3.0.5": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:timers-browserify@1.4.2": {
      "process": "npm:process@0.11.2"
    },
    "npm:uncontrollable@3.2.1": {
      "invariant": "npm:invariant@2.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@0.14.6"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@2.1.0": {
      "loose-envify": "npm:loose-envify@1.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:websocket-driver@0.6.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "net": "github:jspm/nodelibs-net@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "websocket-extensions": "npm:websocket-extensions@0.1.1"
    },
    "npm:websocket-extensions@0.1.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
